### ISSUE TITLE
Presets not working.

### ISSUE THREAD

**Issue by Gremagol** [Zerthox/BetterDiscord-Plugins#1]
Presets are not working, I can save them and its saving them in that file, but I can't load/delete any of them, because they do not show up.
When i just click load, then i get an error in the console:
![presets not working](https://cloud.githubusercontent.com/assets/24619854/26752230/495f862c-484b-11e7-8a73-8f35db121de8.PNG)
Help meh I love this plugin ;-;

**Comment by Zerthox** [comment]
SendEmbeds is getting a rework
