### ISSUE TITLE
BD or even whole Discord crashes after right clicking folder

### ISSUE THREAD

**Issue by Zzeyy** [Zerthox/BetterDiscord-Plugins#104]
BetterDiscord or even the Discord itself is crashing after right clicking a folder and selecting Folder Settings.
I'm running the newest version from Plugin Repo (v3.1.1), also newest BD (v1.5.1).

I cannot explain more as I don't know what's causing it.

**Comment by Zzeyy** [comment]
And opening a folder after another is not closing the other folder.

**Comment by Zerthox** [comment]
Are you on stable Discord? I assume you are getting the Discord crash screen and not a full renderer crash, could you check the console for errors?

**Comment by Zzeyy** [comment]
Hi, I am on stable Discord and I don't know how to access a console.
If you provide enough information on how to access it then I'll happily help.

**Comment by Zzeyy** [comment]
Ctrl+Shift+I is not working for me. So I cannot probably even open the console.

**Comment by Zerthox** [comment]
Assuming this is an issue with BDFDB and may already have been fixed. Closing.
