### ISSUE TITLE
OnlineFriendCount just dead

### ISSUE THREAD

**Issue by YuuJinS** [Zerthox/BetterDiscord-Plugins#105]
![image](https://user-images.githubusercontent.com/34113239/153731313-fbd7614b-d1f7-4677-9c12-53324a6a1389.png)

**Comment by Zerthox** [comment]
Are you Discord stable? Are you using the most recent version of the plugin (v2.1.2)? Could you check the console for errors (enable in BetterDiscord developer settings, then ctrl+shift+i)?
