### ISSUE TITLE
Bettervolume is non functional as of a few days ago

### ISSUE THREAD

**Issue by nippanippa** [Zerthox/BetterDiscord-Plugins#106]
Bettervolume is non-functional as of a few days ago. The plugin broke with (I think) the most recent discord update. I tried manually updating the plugin after it broke, to no avail.
![Discord_jBqV3XBxGS](https://user-images.githubusercontent.com/42161067/153993975-cd902fc0-cd4b-4203-9655-8c9dd23fed64.png)
![Discord_WCumFyXdDD](https://user-images.githubusercontent.com/42161067/153993999-df7b4ade-237b-40d5-a312-6e993092ce40.png)

**Comment by StepCenta** [comment]
Same issue here.

BetterDiscord 1.5.1
Latest Discord stable version

**Comment by Zerthox** [comment]
Are you using the most recent version of the plugin (v2.2.2)? Could you check the console for errors (enable in BetterDiscord developer settings, then ctrl+shift+i)?

**Comment by StepCenta** [comment]
> Are you using the most recent version of the plugin (v2.2.2)? Could you check the console for errors (enable in BetterDiscord developer settings, then ctrl+shift+i)?

I thought that the plugin would update by its own, I still have v1.0.0. I'll get latest version and I'll let you know

**Comment by Zerthox** [comment]
Assuming this has been fixed in a more recent version. Closing.
