### ISSUE TITLE
[VoiceEvents] Can't use speech synthesis voices when they are accessible.

### ISSUE THREAD

**Issue by NotSpaulding** [Zerthox/BetterDiscord-Plugins#107]
## Description

I get an error saying "Electron does not have any Speech Synthesis Voices available on your system." on startup, but running `speechSynthesis.getVoices()` in the console, clearly gives results: ![](https://i.imgur.com/28HKfEX.png)

## Relevant Errors

![](https://i.imgur.com/EqCyYmf.png)

## Extra Information

```log
Stable 114764 (13f4bff) Host 1.0.9003 Windows 10 64-Bit (10.0.19044)
Powercord master (72b3c40) | OpenAsar db0b3f1
Kernel null (undefined)
```
- Using [Kernel](https://github.com/kernel-mod) with [bd-compat](https://github.com/strencher-kernel/bd-compat/tree/0b1e0a16d24f7c89ce60df02ada7dfbefce885dc).

**Comment by Zerthox** [comment]
That seems odd. The message should only ever be shown if `speechSynthesis.getVoices()` is empty.

Any chance you could check if the problem persists with a regular BetterDiscord install? Kernel's bd-compat might be loading the plugin in an incompatible way.

**Comment by NotSpaulding** [comment]
Everything seems to be working fine on BetterDiscord. ![](https://i.imgur.com/G7C5NYX.png)

Not very surprised considering I did not see any other issues about this, I was mainly wondering if there'd be a way to make this plugin work on Kernel?

**Comment by Zerthox** [comment]
Kernel is most likely loading the plugin too early, before speech synthesis voices have been loaded. This is something that should be fixed on their side as loading earlier than BetterDiscord may cause issues with other BetterDiscord plugins as well.

**Comment by NotSpaulding** [comment]
Alright, that's fine; I guess I'll make an issue about this on [strencher-kernel/bd-compat](https://github.com/strencher-kernel/bd-compat), thanks for the help!
