### ISSUE TITLE
Request: Setting for BetterReplyer to ignore self

### ISSUE THREAD

**Issue by just-Addict** [Zerthox/BetterDiscord-Plugins#11]
Would it be possible to add a setting option where one can paste his/her own ID so the button doesn't show on your own posts?

This may sound dumb but when doing support in a busy channel on desktop Discord, it often happens to me that the moment I am about to click that button, a new posts shows up, and sure enough when this happens I usually find myself replying to myself :joy: because one of my previous posts just happens to scroll right under my mouse

**Comment by KaKi87** [comment]
+1

**Comment by Zerthox** [comment]
Added.
