### ISSUE TITLE
[Feature] VoiceEvents: TS3 Female Voice

### ISSUE THREAD

**Issue by MrJktra** [Zerthox/BetterDiscord-Plugins#112]
Hi,

I don't know if it's possible or not but are u able to add the female voice from TS3?

![Screenshot 2022-03-25 174900](https://user-images.githubusercontent.com/101983929/160155315-995e4a5f-8b59-4927-97f6-57c0c8158c1e.png)

**Comment by Zerthox** [comment]
The available speech synthesis voices are the ones installed on your system & available to Electron. Adding the TS3 voice would require you to install the speech synthesis voice used by TS3 in a way that Electron recognizes it.
