### ISSUE TITLE
[BetterVolume] Plugin Gradually Slows Down Text Box Right Click Context Menu

### ISSUE THREAD

**Issue by dottiekh** [Zerthox/BetterDiscord-Plugins#115]
The context menu when right clicking in the text area to type a message will appear gradually slower and slower with this plugin enabled. From plugin start, right clicking in the text area will have the context menu appear at its usual speed as normal, however continuously doing so will have it appear slower and slower until it averages around 700ms response time. This seems to be because for some reason the plugin is running tasks that lock the appearance of the context menu until they complete.

Here is a graph of the performance capture with the plugin disabled:
![image](https://user-images.githubusercontent.com/34873184/162685203-f4dc94f3-b257-4f43-bb5a-ea30f6c9c8bb.png)
Each column is a right click action.

Here is a graph of the performance capture with the plugin enabled, starting from when the context menu appears at its normal speed:
![image](https://user-images.githubusercontent.com/34873184/162685488-0a06ee3b-d958-40f5-8c0b-5e81d963e123.png)
Right click task takes ~200ms average, much like it does normally.

Here is a graph of the performance capture with the plugin enabled, after about 20 or so seconds of it running:
![image](https://user-images.githubusercontent.com/34873184/162685615-daf2afb7-6400-490c-8763-f5925c6115f2.png)
Right click task takes ~600ms average. This maximizes around 750ms or so.
![image](https://user-images.githubusercontent.com/34873184/162686048-a2295c66-4a35-4500-9fd8-d2955565fa2a.png)

I've noticed that in each right click call the BetterVolume.plugin.js is referenced in the bottom up call stack, with the plugin taking an increasing amount of time to process whatever it's doing.
![image](https://user-images.githubusercontent.com/34873184/162685790-be20f172-65b1-443b-954f-269f85605f83.png)

**Comment by Zerthox** [comment]
Actually nevermind, the arguments are not persistent. This seems to be a bug on Discord's side which causes their callback to get called more and more often rather than once.

**Comment by Zerthox** [comment]
Discord still hasn't fixed this bug. However, it should no longer be relevant since the plugins now use a different way of finding lazy loaded modules.
