### ISSUE TITLE
[VoiceEvents]

### ISSUE THREAD

**Issue by Necroclysm** [Zerthox/BetterDiscord-Plugins#117]
Unable to open the settings for VoiceEvents

I hadn't attempted to open this for awhile, so not sure what changed.  I reinstalled Discord last night and when getting everything set back up noticed that it wasn't allowing me to open the settings.

I had someone else check who has had it installed awhile and it doesn't work on his either.  

![image](https://user-images.githubusercontent.com/65626860/169637773-1eab5246-eac6-4e2a-bbf8-18fe832e7f81.png)

**Comment by sudraio** [comment]
Same here

Stable 130832 (367507e)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Comment by Zerthox** [comment]
I forgot to close, this has already been fixed with v2.2.2 in https://github.com/Zerthox/BetterDiscord-Plugins/commit/8088bdd4177b6a3842f1343a612393f11c9db939. Approval for BD site is still pending.
