### ISSUE TITLE
Additional counters for OnlineFriendCount

### ISSUE THREAD

**Issue by Tharki-God** [Zerthox/BetterDiscord-Plugins#118]
make it more than just a friend count but make it like this
so that it cycles throw all these statistics either on click or set interval in settings.
![yog4NAGa6G](https://griefmodz.xyz/uploads/yog4NAGa6G.gif)

**Comment by Tharki-God** [comment]
I made it into plugin myself

**Comment by Zerthox** [comment]
Keeping this open as tracking issue for additional counters.

**Comment by Tharki-God** [comment]
Oki my love

**Comment by Zerthox** [comment]
Added preliminary support for other counters in the upcoming version.
