### ISSUE TITLE
Discord update breaking all plugins

### ISSUE THREAD

**Issue by satoon10** [Zerthox/BetterDiscord-Plugins#124]
```
TypeError: Cannot read property 'Store' of undefined
    at eval (betterdiscord://plugins/BetterVolume.plugin.js:151:29)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)
```

**Comment by jowslive** [comment]
same issue here o/

**Comment by Zerthox** [comment]
All plugins are broken due to Discord making major internal changes in a recent silent update. May take some time until they are fixed.

**Comment by Infinitay** [comment]
I noticed you are slowly updating the plugins. First and foremost thank you. Secondly, will you be distributing the updates all at once like you did prior (https://github.com/Zerthox/BetterDiscord-Plugins/tree/master/dist/bd) or is it possible for you to do so individually? I tried looking into Actions and couldn't find an action for building the plugins there either.

Thanks again.

**Comment by Zerthox** [comment]
Updating the plugin files in the `dist` folder issues an update to be reviewed for the BetterDiscord site (for the ones listed there). If you'd like to build them from the current state of their source files, you can clone the repo and build them yourself. Installing dependencies & building requires Node.js to be installed.

Only BetterVolume and NoReplyMention (highly simplified version of SupressReplyMentions I made for personal use) are in a somewhat functional state as of writing this comment. A fixed version of BetterVolume should be released soon hopefully.

**Comment by Infinitay** [comment]
I wasn't aware. I'll go ahead and build the plugins myself in that case. Thank you.

**Comment by Zerthox** [comment]
BetterVolume is now updated in the repo and awaiting approval for the BetterDiscord site.

**Comment by Zerthox** [comment]
OnlineFriendCount and VoiceEvents are fixed as well by now. BetterFolders will hopefully follow soon.

**Comment by gamingoffice** [comment]
do you already know when youre able to update the BetterFolders Plugin 
because its a lifesaver plugin for me xD

**Comment by Zerthox** [comment]
A fixed version is already available in this repo. However, it's still pending for approval on the BD site. I'm keeping this open until it's approved.

**Comment by gamingoffice** [comment]
> 

Ok i updated it now manually but i cant open my folders to the right site like it was able before

**Comment by Zerthox** [comment]
> Ok i updated it now manually but i cant open my folders to the right site like it was able before

Not sure what you mean by that. All the functionality of the plugin should be restored. It does sound a bit like it may have been something else adding this functionality?

**Comment by asorel1942** [comment]
I just attempted downloading the BetterFolders plugin directly from this repo. I no longer get the TypeError that everyone was first getting after the Discord update, but instead I now get a "META was not found" error. The error HTML generated is very lengthly but it begins like this:

```
<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" data-a11y-animated-images="system">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">
```

**Comment by Zerthox** [comment]
You downloaded the wrong file - the Github page displaying the plugin file instead of plugin file itself. Click on the `raw` button, then download that.

**Comment by Zerthox** [comment]
BetterFolders update has been approved. Closing.
