### ISSUE TITLE
OnlineFriendCount Instability in Server List

### ISSUE THREAD

**Issue by KingGamingYT** [Zerthox/BetterDiscord-Plugins#126]
OnlineFriendCount's little indicator disappears & reappears repeatedly while scrolling, causing instability & jitter in the server list as you scroll up and down.

https://user-images.githubusercontent.com/45918062/195993309-38e3818d-c6b1-4a24-bdfb-4bcf45b49ec3.MP4

_this was initially posted as an issue in the BetterDiscord support server, where I was told to redirect it to the main plugin dev._

**Comment by Zerthox** [comment]
Thanks for reporting. Released a fix.
