### ISSUE TITLE
BetterVolume Slider is broken when sliding

### ISSUE THREAD

**Issue by IncogPanda** [Zerthox/BetterDiscord-Plugins#132]
When sliding the bar just slightly it would go up and slide very fast. I tried reinstalling it and still have the issue. I could just type in the # but sometimes I want to use the slider.

**Comment by Zerthox** [comment]
I'm assuming this is about BetterVolume. The slider stays completely untouched by the plugin. This is a bug on Discord's side, it also happens with the plugin disabled and in vanilla Discord.
