### ISSUE TITLE
[BetterFolders] BetterDiscord Crashes when "custom icon" is selected

### ISSUE THREAD

**Issue by Musta-VG** [Zerthox/BetterDiscord-Plugins#138]
### Bug description

Whenever the custom icons option is selected on ANY folders it will instantly crash
This is confirmed to be only BetterFolders' issue, other than that BD is working fine

Sadly I can't open the console so that's all I can say

### Plugin

BetterFolders

### Plugin version

v3.4.0

### Discord client

Stable

**Comment by Zerthox** [comment]
You can download a fixed version from this repository now. Update on the BetterDiscord site is pending for approval.
