### ISSUE TITLE
[BetterReplyer] Mention in the middle of the message

### ISSUE THREAD

**Issue by KaKi87** [Zerthox/BetterDiscord-Plugins#14]
Hi,

Everything is in the title : I would like to be able to `@` someone in the middle of my sentence, is that possible ?

Thanks !

**Comment by KaKi87** [comment]
@Zerthox ?

**Comment by Zerthox** [comment]
I'll look into it when I update BetterReplyer.

**Comment by Zerthox** [comment]
Updated BetterReplyer. If you have your cursor in the textarea when clicking the reply button, it should insert the mention at your cursor position. If you don't have your cursor in the textarea when clicking the reply button, it will insert the mention at the start of the textarea.
