### ISSUE TITLE
[BetterFolders] Custom Icon setting missing on Stable, not Canary

### ISSUE THREAD

**Issue by maenDisease** [Zerthox/BetterDiscord-Plugins#143]
### Bug description

Option to choose a custom icon for a folder only works on Discord Canary, not Stable
![image](https://user-images.githubusercontent.com/90428263/223578090-a29580c7-68dc-4b0f-851f-33c2b8c9ad29.png)
![image](https://user-images.githubusercontent.com/90428263/223578125-3659f933-979c-4931-be98-9ce12d3f756d.png)

### Plugin

BetterFolders

### Plugin version

3.4.1, 3.4.2

### Discord client

Stable

**Comment by Zerthox** [comment]
Discord messing around with the sorted guild store yet again. Since you said it's fine on canary, I have decided to wait until they figure out how they want it and stop changing things.

**Comment by Zerthox** [comment]
Seems like they figured it out and deprecated one of the relevant stores.
