### ISSUE TITLE
[OnlineFriendCount] Placed in a weird place

### ISSUE THREAD

**Issue by foursplaysroblox** [Zerthox/BetterDiscord-Plugins#144]
### Bug description

Hello I just started discord ptb and I noticed this bug
![image](https://user-images.githubusercontent.com/82078139/224516205-51eb7b5b-3188-4498-8612-2809c8c7089f.png)

It also happens without a theme applied 
![image](https://user-images.githubusercontent.com/82078139/224516235-d0bd2fcc-5697-4461-bd1b-33199751ca62.png)

### Plugin

OnlineFriendCount

### Plugin version

v3.1.0

### Discord client

PTB

**Comment by foursplaysroblox** [comment]
discord update?

**Comment by TheAdrians** [comment]
> discord update?

Yes

**Comment by foursplaysroblox** [comment]
It is fixed now
