### ISSUE TITLE
CollapseEmbeds expand image on hover when there are multiple images

### ISSUE THREAD

**Issue by longxa762** [Zerthox/BetterDiscord-Plugins#146]
### Bug description

https://imgur.com/a/kJoFZs8

Latest Discord update seem to broke it?

### Plugin

CollapseEmbeds

### Plugin version

1.0.0

### Discord client

Stable

**Comment by Zerthox** [comment]
Unable to reproduce, are you certain it is the plugin and there are no other plugins affecting it?

**Comment by longxa762** [comment]
I found the problem, it's seem to be a conflicting issue with another plugin, "[ImageUtilities](https://betterdiscord.app/plugin/ImageUtilities)" by [DevilBro](https://betterdiscord.app/developer/DevilBro). Having both of them ON will cause the issue.

**Comment by Zerthox** [comment]
You should probably report this for ImageUtilities then. CollapseEmbeds only adds some additional elements & adjusts the way elements are aligned, ImageUtilities seems to be the one doing some weird height modifications that cause the bug.

**Comment by longxa762** [comment]
I will go and do that
