### ISSUE TITLE
VoiceEvents: Clicking settings throws error

### ISSUE THREAD

**Issue by AceLikesGhosts** [Zerthox/BetterDiscord-Plugins#149]
### Bug description

Clicking on the VoiceEvent's settings button throws an error.

Stacktrace: https://paste.gg/p/anonymous/b9bb8e5c7dd546829836974be501794b/files/38e7827e7b2b47daa0f8d38cda357550/raw
![image](https://user-images.githubusercontent.com/46033729/230696093-026c69a4-474e-43ac-ae48-970bc40a9001.png)

### Plugin

VoiceEvents

### Plugin version

v2.5.1

### Discord client

Stable

**Comment by Zerthox** [comment]
Select & Switch components missing.

**Comment by Zerthox** [comment]
Update approved for BetterDiscord site. Closing.
