### ISSUE TITLE
BetterFolders - discord crashes when setting up custom icon

### ISSUE THREAD

**Issue by Zanzazaar** [Zerthox/BetterDiscord-Plugins#150]
### Bug description

Discord crashes when the user selects the "Custom Icon" option.

### Plugin

BetterFolders

### Plugin version

3.4.3

### Discord client

Stable

**Comment by AprilLR** [comment]
Having the same issue.

**Comment by Maarten-1044232** [comment]
same here

**Comment by itzShazo** [comment]
same here

**Comment by Zerthox** [comment]
Update approved for BetterDiscord site. Closing.
