### ISSUE TITLE
CollapseEmbeds - trying to open the plugion settings menu causes error

### ISSUE THREAD

**Issue by grayson676** [Zerthox/BetterDiscord-Plugins#152]
### Bug description

After installing the Collapseembeds plugin, going to the plugin menu in betterdiscord and trying to open the settings menu for Collapseembeds fails, states "there was an unexpected Error. Click to open console  for more details."
In the console the error listed is 

"7d5f340666fed72b4bca.js:241 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

  Going to the reactjs website says that the error is "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined."

### Plugin

CollapseEmbeds

### Plugin version

v1.0.0

### Discord client

Stable

**Comment by Zerthox** [comment]
Update approved for BetterDiscord site. Closing.
