### ISSUE TITLE
Can't open Settings button, Error Message

### ISSUE THREAD

**Issue by xFanexx** [Zerthox/BetterDiscord-Plugins#161]
### Bug description

I cant open the Settings from the plugin, it shows an error > 
![grafik](https://github.com/Zerthox/BetterDiscord-Plugins/assets/144341049/84a7c720-971d-49ba-acf5-4b9f8b29e86b)

![grafik](https://github.com/Zerthox/BetterDiscord-Plugins/assets/144341049/2c0efa00-59a9-4ee0-84d1-91b0621a1256)

![grafik](https://github.com/Zerthox/BetterDiscord-Plugins/assets/144341049/d3705fae-20ba-4762-8401-930dd9b8fe81)

### Plugin

BetterVolume

### Plugin version

v2.4.1

### Discord client

Stable

**Comment by Zerthox** [comment]
Same issue as #160.
