### ISSUE TITLE
BetterFolders plugin crash

### ISSUE THREAD

**Issue by 4n0nct** [Zerthox/BetterDiscord-Plugins#166]
### Bug description

After the last discord update, the plugin will make discord freeze and crash if we click on another folder than the one we are currently in. Same result in BD and Vencord. Once the plugin is disabled no crash or freeze occurs.
Also, while crashing, will make CPU usage skyrockets

### Plugin

BetterFolders

### Plugin version

v3.4.5

### Discord client

Stable

**Comment by Zerthox** [comment]
I have been unable to reproduce this behavior so far. Are you running any other plugins that could cause incompatibility issues?

**Comment by 4n0nct** [comment]
I just received the last update of vencord and it fixed it with some other things, thank you for having tested it on your side. I will close it as resolved, have a nice day.
