### ISSUE TITLE
CollapseEmbeds crash loop.

### ISSUE THREAD

**Issue by ItMeSarah** [Zerthox/BetterDiscord-Plugins#168]
### Bug description

CollapseEmbeds causes crash loop when entering channels and dms with embeds, likely broke with the discord module & class changes. 
![image](https://github.com/Zerthox/BetterDiscord-Plugins/assets/67713330/c4e4af76-3183-4d4e-8e37-d723865e8304)

### Plugin

CollapseEmbeds

### Plugin version

v1.0.3

### Discord client

Stable

**Comment by gohamstergo** [comment]
1.0.4 fixes it for me
