### ISSUE TITLE
Insane Performance Issues with BetterFolders on

### ISSUE THREAD

**Issue by Kagetora120903** [Zerthox/BetterDiscord-Plugins#170]
BetterFolders makes Discord insanely slow, laggy and freezes a lot => causes performance issues on a fairly good setup

I am on the latest version of the plugin and on the latest version of Discord (and BD) and I've been getting these issues for the past 2 weeks (and the previous versions since the last 2 weeks).

Tried with Hardware acceleration on and off and both were horribly laggy. 

System :
- Win11
- rtx 3060
- ryzen 7 5800h (laptop)
- 16GB RAM
- discord (and BD) on an SSD (50% filled)

**Comment by Zerthox** [comment]
What Discord client are you on (stable, PTB, canary)? What other plugins are you running? What icons/settings are you using with BetterFolders?

**Comment by Kagetora120903** [comment]
I'm running on discord's latest stable version. Default settings on everything, mostly JPG images.
For the plugins I found out what's going on, I think there's some compatibility issues with YABDP4Nitro plugin (by Riolubruh). Running both seperately (with the other disabled) everything works fine but as soon as both are enabled at the same time, discord gets very laggy. Should I start a bug thread on Riolubruh's github too?

**Comment by Zerthox** [comment]
Quick glance over the code gives me the impression the performance issues are caused on YABDP4Nitro's side. Considering it's not an approved plugin, I won't be investing any more time towards this for now. You should open an issue on their github.
