### ISSUE TITLE
Plugin Meta of BetterFolders not found

### ISSUE THREAD

**Issue by Develeon64** [Zerthox/BetterDiscord-Plugins#173]
### Bug description

Since the last bigger Update of Discord (about 2 months ago) and updating BD and all plugins BetterFolders can't be stated. The error message says, that the plugin ``Meta`` cannot be found.

The exact error message is some HTML from NGINX saying there is a ``502 Bad Gateway`` error. It also contains a beacon script from CloudFlare.
I would post the full raw message, but it contains IDs and Tokens and I don't know, which of them are too sensitiv to do so. But maybe this set of information is enough for you. Otherwise just ask :)

### Plugin

BetterFolders

### Plugin version

3.4.6

### Discord client

Stable

**Comment by Zerthox** [comment]
Sounds like you attempted to update while the BetterDiscord site was down. Try redownloading the plugin.

**Comment by Develeon64** [comment]
Thanks for your reply!

Very strange. I have done so many times a few days in row. I tried with the Plugin-Repo and to download it from the website manually. Almost with the same result.

That's why I stopped trying that at some point waiting for an update.
Now I tried it again and it just helped.

Thank you!
