### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by Killer31g** [Zerthox/BetterDiscord-Plugins#193]
### Bug description

for a few days the plugin doesnt work and this is the notification thats showing up
![obraz_2024-11-17_143925045](https://github.com/user-attachments/assets/47195eef-af22-473f-8c26-69350dd3105f)

### Plugin

BetterVolume

### Plugin version

v3.0.0

### Discord client

Stable

**Comment by Zerthox** [comment]
See #190, either you tempered with the plugins settings file or this was caused by a bug in BetterDiscord. Removing `BetterVolume.config.json` should make it work again.
