### ISSUE TITLE
[BetterVolume] Cannot specify a value higher than 200%

### ISSUE THREAD

**Issue by Lusiiky** [Zerthox/BetterDiscord-Plugins#194]
### Bug description

Hello,

The problem has been there for several weeks, several months, and I never took the time to make an issue here... but now that I see that no one has reported the problem and the problem has not been corrected, I felt compelled to do so.

The problem is that it's just not possible for me to specify a volume greater than 200% or else the volume will automatically set to a negative volume.

I don't know exactly what's causing this but... well, I had to ask this problem here, because the mod doesn't work in my case.

Thank you,
Lusiiky

Infos:
ptb 347971 (4a86a9a) Host 1.0.1118 x64 (55751) Build Override: N/A Windows 11 64-bit (10.0.26100)

### Plugin

BetterVolume

### Plugin version

v3.0.0

### Discord client

PTB

**Comment by Lusiiky** [comment]
@Zerthox
> Seems the plugin has some issues when it's loaded before Discord has fully loaded. Try disabling and reenabling it after starting/reloading Discord. I'll release a new version that hopefully fixes this issue.

You're right. Thanks for the workaround!
Looking forward to the update then :)

**Comment by VeryEvilBatman** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/9ee8a51b-60d6-4492-80e4-0e7c5f064427)
