### ISSUE TITLE
Online Counter Not Working after newest Update

### ISSUE THREAD

**Issue by TCPubKibbles** [Zerthox/BetterDiscord-Plugins#20]
I noticed from the new guild list selector update that got pushed yesterday, the friends online counter was broken also and now doesn't work at all. Hoping it can be fixed as I love this plugin!

**Comment by Zerthox** [comment]
Fixed with https://github.com/Zerthox/BetterDiscord-Plugins/commit/d0f05713d78e0f17f6a2102a9688ab044c3cbf48.
