### ISSUE TITLE
BetterReplyer

### ISSUE THREAD

**Issue by HYPExMon5ter** [Zerthox/BetterDiscord-Plugins#25]
Better replyer errors on startup everytime I load discord and has for about a week or so. Figured I'd report it. 
![Discord_NS0losVVVg](https://user-images.githubusercontent.com/12315186/74596461-724acd80-501d-11ea-95f7-2f76613b0288.png)

**Comment by Zerthox** [comment]
What version of BetterReplyer are you running?

**Comment by HYPExMon5ter** [comment]
4.3.0. I re-downloaded and it doesn't error anymore, the button to reply is non-existent, though.

**Comment by Zerthox** [comment]
I'm unable to recreate that issue. Did you swap channels after enabling the plugin? The current version no longer force updates on its own, you have to trigger a rerender manually. Are there any errors in the devtools console? Maybe conflicting plugins?

**Comment by holysnipz** [comment]
All Themes + Plugins but BetterReplyer disabled

with 'Normalize Classes' off in BBD settings, working fine
![2020-02-24_16-09-27](https://user-images.githubusercontent.com/9103583/75139777-11f41400-5720-11ea-9eb9-d2af7bc9500a.gif)

with 'Normalize Classes' on in BBD settings, the button is there but won't show when hover
![2020-02-24_16-06-57](https://user-images.githubusercontent.com/9103583/75139688-d5281d00-571f-11ea-83e3-08f23ae86139.gif)

**Comment by Zerthox** [comment]
Ah normalized classes, I always forget those still exists.
