### ISSUE TITLE
voicevents: cannot read propertie 'name'

### ISSUE THREAD

**Issue by LeSnake04** [Zerthox/BetterDiscord-Plugins#27]
getting these error while building plugin.

**Comment by alx365** [comment]
I have the same issue.

**Comment by Zerthox** [comment]
Are you on the most recent version? Do you have speech synthesis voices available on your system? The Plugin assumes that there is at least one voice available, if there is none it will crash.

**Comment by LeSnake04** [comment]
i have v1.1.1 and festival,  speech-dispatcher libspeechd espeak-ng and espeak-ng-espeak installen 
(i use arch linux)

**Comment by Zerthox** [comment]
Is electron able to pick those up? You can check by running `speechSynthesis.getVoices()` in console, it gives you an array with available speech synthesis voices.

I guess I should add a check to the plugin that reports when it is unable to find any speech synthesis voices.

**Comment by LeSnake04** [comment]
![Bildschirmfoto_2020-04-17_21-40-20](https://user-images.githubusercontent.com/47243761/79607764-13c0cf00-80f4-11ea-973f-be522bf6f841.png)
scheinbar nicht...

**Comment by alx365** [comment]
bruh sind denn alle deutsch? well i too have festival installed and i am on manjaro (a deritave from arch)

**Comment by Zerthox** [comment]
Added a check & alert modal for no voices with https://github.com/Zerthox/BetterDiscord-Plugins/commit/5887ecf2b933847559269744d1f4b7fb50f4dd73.

Related:
https://github.com/electron/electron/issues/586
https://stackoverflow.com/questions/46863170/speechsynthesis-getvoices-is-empty-array-in-chromium-fedora

**Comment by alx365** [comment]
Can you keep us informed?

**Comment by Zerthox** [comment]
I'll close this since it's not the plugins fault.
