### ISSUE TITLE
BetterFolders v2.1.0 could not be started

### ISSUE THREAD

**Issue by Anach** [Zerthox/BetterDiscord-Plugins#29]
Recent updates to BD have stopped this plugin from loading (typical, right after I make new folder icons lol)

**Comment by zany130** [comment]
same for me

**Comment by Zerthox** [comment]
Fixed with https://github.com/Zerthox/BetterDiscord-Plugins/commit/5945a23e34d3b76a329880b7d1dc0fd9f9b6e6b7.
