### ISSUE TITLE
Online Friend Count no longer working after latest update.

### ISSUE THREAD

**Issue by SnowyHuskybutt** [Zerthox/BetterDiscord-Plugins#30]
Ever since Discord has updated recently, this plugin no longer works at all. It says that it cannot start and it just brings up errors in the console. Hopefully it can be fixed soon, I use this plugin regularly.

**Comment by Zerthox** [comment]
Fixed with https://github.com/Zerthox/BetterDiscord-Plugins/commit/133119eb218932722c4b019729511dd2208d50e9.
