### ISSUE TITLE
BetterReplyer 4.3.3: Unable to find header element in MessageHeader component.

### ISSUE THREAD

**Issue by Bilibox** [Zerthox/BetterDiscord-Plugins#35]
```
\BetterDiscord\plugins\BetterReplyer.plugin.js:180 [BetterReplyer] (v4.3.3) Unable to find header element in MessageHeader component
error @ \BetterDiscord\plugins\BetterReplyer.plugin.js:180
after @ \BetterDiscord\plugins\BetterReplyer.plugin.js:110
(anonymous) @ remote.js:1
e.<computed> @ remote.js:1
callOriginalMethod @ remote.js:1
Object @ remote.js:1
callOriginalMethod @ BDFDB.min.js:1
(anonymous) @ BDFDB.min.js:1
Object @ BDFDB.min.js:1
_a @ ddd49d192c56097b2a38.js:78
Rs @ ddd49d192c56097b2a38.js:78
yu @ ddd49d192c56097b2a38.js:78
Iu @ ddd49d192c56097b2a38.js:78
cu @ ddd49d192c56097b2a38.js:78
(anonymous) @ ddd49d192c56097b2a38.js:78
t.unstable_runWithPriority @ ddd49d192c56097b2a38.js:86
zi @ ddd49d192c56097b2a38.js:78
Ji @ ddd49d192c56097b2a38.js:78
Qi @ ddd49d192c56097b2a38.js:78
fu @ ddd49d192c56097b2a38.js:78
Rn @ ddd49d192c56097b2a38.js:78
r @ f7b6df084c785536f555.js:16
```

Console Error. This gets spammed when opening in a Guild. While this is specifically written it's bad practice to spam the console with errors.
Canary 65844 (58bd42b)
BBD 0.3.5
Host 0.0.272
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Comment by master3395** [comment]
You should try QuickMention v1.0.1 by DevilBro
This one works.

[https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/QuickMention](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/QuickMention)

**Comment by Zerthox** [comment]
> While this is specifically written it's bad practice to spam the console with errors.
This has nothing to do with bad practice, the component is rendered in every MessageGroup component, so you will get the error once for every message group attempting to render onscreen.

I'm assuming this was a canary update that got rerolled, the message components for stable & canary seem to be the same and the are no issues with the plugin currently. Keep in mind nearly all BD plugins are developed for use on stable, issues on canary may not be fixed until the update makes its way to stable.
