### ISSUE TITLE
Emulator plugin set to MacOS from Windows 10 compelely breaks game streaming

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [Zerthox/BetterDiscord-Plugins#39]
While on Windows 10, if I set it to MacOS, it completely prevents me from streaming my game to Discord— the game doesn't even show up in the stream menu. The keybinding option for streaming also completely disappears.

**Comment by Zerthox** [comment]
I believe this is due to streaming not being fully available on MacOS. The emulator makes Discord's rendering think you are on a different operating system, so it will not display anything related to game streaming if Discord does not support game streaming on said operating system.
