### ISSUE TITLE
Bug with groovy bot

### ISSUE THREAD

**Issue by PoggersInTheChat** [Zerthox/BetterDiscord-Plugins#45]
For some reason, when groovy bot is playing an audioit will sometimes trigger the "leave channel" TTS

https://user-images.githubusercontent.com/74301970/110675288-01032d00-81d3-11eb-9f6f-48b59c82798e.mp4

in this video you can hear the TTS looping the message over and over, it kept going for about a minute

**Comment by Zerthox** [comment]
Hmm this is likely due to Groovy being connected on multiple channels in servers you are in. I'll have to see if it's possible to distinguish between multiple connections and moving to another channel.
