### ISSUE TITLE
[feature] more Voice Envents

### ISSUE THREAD

**Issue by SirVoRaK** [Zerthox/BetterDiscord-Plugins#51]
Add voice events for mute and deafen, like "USER muted" and "USER deafen"
If you mute/deafen: "Microphone muted" and "deafen"

**Comment by xamionex** [comment]
> Add voice events for mute and deafen, like "USER muted" and "USER deafen"
> If you mute/deafen: "Microphone muted" and "deafen"
Install NotificationSounds by DevilBro
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/NotificationSounds

**Comment by Zerthox** [comment]
> Add voice events for mute and deafen, like "USER muted" and "USER deafen"
I feel like this is out of scope for the plugin. It's supposed to be a tool inform you about users leaving/joining voice channels, not to stalk other users.

> If you mute/deafen: "Microphone muted" and "deafen"
This could certainly be added. Can't promise when/if I will implement it. Feel free to submit a PR if you like.

**Comment by Zerthox** [comment]
Closing in favor of #103.
