### ISSUE TITLE
feature [better volume]

### ISSUE THREAD

**Issue by Corentin-Rougeon** [Zerthox/BetterDiscord-Plugins#53]
add the ability to set the volumes of stream to 100+%

**Comment by ufgf** [comment]
there is a plugin that implements this, but only for users: https://github.com/QWERTxD/BetterDiscordPlugins/tree/development/UserVolumeBooster , it may well make sense to ask that developer to implement it, or perhaps make a single plugin that will combine this idea, BetterVolume and UserVolumeBooster? 🙃

**Comment by Zerthox** [comment]
Forgot to close this, this is already possible with BetterVolume. Right click the stream and change the volume in the context menu. Volumes are not capped to 200% when using BetterVolume's number input.
