### ISSUE TITLE
[Feature Request] Microsoft Natural Voices - Is it possible?

### ISSUE THREAD

**Issue by saraprc-dev** [Zerthox/BetterDiscord-Plugins#57]
Great plugin! Works as intended, although the voices may come as a bit off-putting. Is there a way to use Microsoft's Natural Voices like in this site? 

https://voicegenerator.io/

**Comment by Zerthox** [comment]
Using an online speech synthesis voice is currently not possible with the plugin. It uses the Web SpeechSynthesis API, which means the speech synthesis voices have to be installed on your system and in a way that Electron can use them.
 
 If you'd like to have the option to use online speech synthesis voices, you can feel free to submit a PR.
