### ISSUE TITLE
OnlineFriendCount v1.4.1 could not be started

### ISSUE THREAD

**Issue by kingwexx** [Zerthox/BetterDiscord-Plugins#58]
hello, I have been using your plugins for a long time and today I ran into a problem that one of your plugins called OnlineFriendCount does not work and gives the following error:
![image](https://user-images.githubusercontent.com/87783731/126558817-37e3f18e-1296-4393-a9c0-3126f25c7b9f.png)

Could you fix this? I will be very grateful to you!

**Comment by Zerthox** [comment]
This is due to an issue with a part the BetterDiscord plugin API. A recent silent update seems to have broken it. Will likely be fixed very soon.
