### ISSUE TITLE
Online friend count crash

### ISSUE THREAD

**Issue by canerolu2019** [Zerthox/BetterDiscord-Plugins#60]
Whenver i want to activate this plugin it doesnt work. It always crashes when i try to enable it. When i toggle the button for activation it disables itself for some strange reason. Can you pls fix this. Thank you.

**Comment by Zerthox** [comment]
This was an issue with the BetterDiscord API. OnlineFriendCount should be working again as of the BD update a few hours ago (v1.2.1).
