### ISSUE TITLE
[bug] better volume no longer boosts volume beyond 200

### ISSUE THREAD

**Issue by aaaddd4747** [Zerthox/BetterDiscord-Plugins#63]
a recent discord update seems to have broken this aspect of the plugin.

i rely on the plugin to alleviate issues with some of my friend's mics which are incredibly unfixably low. 

the plugin still allows selecting volumes higher than 200 but doing so has no effect.

**Comment by Zerthox** [comment]
I'm unable to reproduce this. For me there is still a very clear difference between 200% and 500% volume on Discord stable as of today.
