### ISSUE TITLE
Error on recent updates

### ISSUE THREAD

**Issue by Valen-H** [Zerthox/BetterDiscord-Plugins#66]
![console](https://user-images.githubusercontent.com/20339324/136519814-b5884ff9-9093-43cc-9b03-d1bb841425bb.png "console logs")

**Comment by Apceniy** [comment]
![image](https://user-images.githubusercontent.com/53149450/136652800-35e12feb-429d-4b01-8e42-01d023651b78.png)
Another POV

**Comment by rexelbartolome** [comment]
After the recent BDFDB update, mine works now for some reason? But it's still buggy.

It keeps saying that BetterFolders could not be started when I enable or disable it in the Plugins menu but regardless, it's already enabled and working and I can see it affect my actual UI on Discord. So I guess the issue on my side is I wouldn't be able to disable it 🤷‍♂️

**Comment by sighofrelief** [comment]
Same here, no longer working.

**Comment by AlexaRVal** [comment]
I hate to say, but it doesn't create the section when you click on the folder like it used to. It still doesn't work properly-
