### ISSUE TITLE
[Bug] [VoiceEvents] VoiceEvents could not be started

### ISSUE THREAD

**Issue by bbeenn1** [Zerthox/BetterDiscord-Plugins#76]
**Plugin**
VoiceEvents v1.6.0 
*currently shows as most recent version available as of Nov 1, 2021 and is unable to be started*

**Discord Version**
Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Comment by Zerthox** [comment]
A fix has been released with v1.6.1 5 days ago, but the update is still not approved for the BetterDiscord website. You can wait or manually download the most recent version from [here](https://github.com/Zerthox/BetterDiscord-Plugins/blob/master/v1/VoiceEvents.plugin.js).
