### ISSUE TITLE
Betterfolders is not working anymore.

### ISSUE THREAD

**Issue by vl3214** [Zerthox/BetterDiscord-Plugins#77]
One day the plugin just said that it stopped, and ever since then I have been unable to start it up. I have reinstalled the plugin multiple times and also completely reinstalled better discord so I don't think the issue is on my end.

**Comment by zany130** [comment]
yeah it lookslike it needs to be updated for the latest version

**Comment by stephiebunnie** [comment]
Yea I've the same issue on normal live discord and my discord canary. 
I've reinstalled plugin and BetterDiscord still unable.

**Comment by BlueStarBRS** [comment]
i have the same issue

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/142081400-b4b62f1a-1171-4b1a-8e94-dd1be6261a7a.png)
if i activate it is just disabled everytimeif i go back in its shows me its disabled over and over again

**Comment by sighofrelief** [comment]
Is there any update on this?

**Comment by BlueStarBRS** [comment]
thx for the fix! @Zerthox (Ehrenmann)
