### ISSUE TITLE
Better Folders is crashing after Today's update.

### ISSUE THREAD

**Issue by HYPExMon5ter** [Zerthox/BetterDiscord-Plugins#79]
I went through each plugin that was updated today as my discord started crashing and I've narrowed it down to this plugin.

**Comment by Zerthox** [comment]
Are you on the most recent versions of BetterFolders, BetterDiscord & Discord stable? Any other details on the crash?

**Comment by HYPExMon5ter** [comment]
Yeah I'm running latest build of BetterDiscord and Discord Stable, when I launched today it said 3 plugins had an update, BetterFolders being one, and it crashed after updating so I removed all 3 and added them back one by one and it didn't crash until I added BetterFolders. I have no other info unfortunately. I tried redownloading the plugin and I also tried repairing BetterDiscord, none of which fixed it.

**Comment by panicthescaredycat** [comment]
Same here, Everything's updated, and it crashes discord, had to remove the plugin through the Plugin folder for it to start up without crashing.

**Comment by ImRushaa** [comment]
Same here : \ everything up to date and the plugin crash Discord.

**Comment by wilecoyote** [comment]
Same here. Disabled the plugin via plugins.json. Funny detail: The plugin crashes only on startup of all Discord versions. If you enable it after Discord has started it's working fine.

**Comment by Iota147** [comment]
Having this issue as well. Was able to capture some log info with the help of BetterDiscord and using the dev tools in Discord. Unlike what WileCoyote said above, the moment I activate it, it just completely crashes out to the "Well this is awkward" page. Whether it's active on load or not doesn't matter.
Info about the build and OS:
Stable 105304 (5f6effe)
BetterDiscord 1.3.0
Host 1.0.9003 
Windows 10 64-Bit (10.0.19044)

[debug.log](https://github.com/Zerthox/BetterDiscord-Plugins/files/7570126/debug.log)

**Comment by Zerthox** [comment]
Could you check whether renaming/moving the `BetterFolders.config.json` in your BD plugins folder has an effect on the issue?

**Comment by wilecoyote** [comment]
> Could you check whether renaming/moving the `BetterFolders.config.json` in your BD plugins folder has an effect on the issue?

No more crashes when the 'BetterFolders.config.json' got deleted.

**Comment by Zerthox** [comment]
Seems like the backwards compatibility for the folder settings has some issues. Could anyone experiencing crashes share their settings file?

**Comment by ImRushaa** [comment]
> Seems like the backwards compatibility for the folder settings has some issues. Could anyone experiencing crashes share their settings file?

How do i do that? And which file do i need to share? I can help : )

**Comment by wilecoyote** [comment]
BetterFolders.config.json v2.4.0:
`{
    "settings": {
        "closeOnOpen": true
    }
}
`
BetterFolders.config.json v3.0.1:
`{
    "settings": {
        "closeOnOpen": true,
        "folders": {}
    }
}
`
