### ISSUE TITLE
BetterVolume not visually compatible with UserVolumeBooster

### ISSUE THREAD

**Issue by Jacketylon** [Zerthox/BetterDiscord-Plugins#80]
I have both the BetterVolume and UserVolumeBooster plugins, but when i type a value into the BetterVolume box within 200%, it changes the slider (which is of 400%) to the position as if it were only 200%. Luckily it doesn't impact the actual volume of the user.

**Comment by Zerthox** [comment]
This is intended behavior. If you type in 200%, why would you expect a value other than 200% on the slider?

Note that the number input from BetterVolume is not capped at 200%. It currently allows you to set volumes as high as 999999%. So you don't need UserVolumeBooster to go above 200%.
