### ISSUE TITLE
Better Volume Could not be constructed 

### ISSUE THREAD

**Issue by Sarreos** [Zerthox/BetterDiscord-Plugins#83]
BetterVolume: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:307996)
    at Object.loadAddon (<anonymous>:4:269972)
    at Object.loadAddon (<anonymous>:4:307108)
    at FSWatcher.<anonymous> (<anonymous>:4:267831)

Using latest version

**Comment by Zerthox** [comment]
Are you on Discord stable? Can you check the console for additional error information?

**Comment by Sarreos** [comment]
I am on stable 

Here is console info:
[BDFDB] (v2.0.3) USER_SETTINGS_VOICE_INSTALLED_LABEL not found in BDFDB.LanguageUtils.LanguageStrings
(anonymous) @ 8799fc073394b31a5a71.js:130
module.exports.InternalBDFDB.console @ 0BDFDB.plugin.js:173
module.exports.BDFDB.LogUtils.warn @ 0BDFDB.plugin.js:179
get @ 0BDFDB.plugin.js:4521
render @ PluginRepo.plugin.js:497
Xo @ 72001f09f5dc9cab20d0.js:6189
qo @ 72001f09f5dc9cab20d0.js:6189
$s @ 72001f09f5dc9cab20d0.js:6229
Gu @ 72001f09f5dc9cab20d0.js:6219
Uu @ 72001f09f5dc9cab20d0.js:6219
wu @ 72001f09f5dc9cab20d0.js:6219
Au @ 72001f09f5dc9cab20d0.js:6216
(anonymous) @ 72001f09f5dc9cab20d0.js:6161
t.unstable_runWithPriority @ 72001f09f5dc9cab20d0.js:6460
Ki @ 72001f09f5dc9cab20d0.js:6161
Xi @ 72001f09f5dc9cab20d0.js:6161
qi @ 72001f09f5dc9cab20d0.js:6161
Tu @ 72001f09f5dc9cab20d0.js:6213
enqueueForceUpdate @ 72001f09f5dc9cab20d0.js:6165
h.forceUpdate @ 72001f09f5dc9cab20d0.js:6431
BDFDB.ReactUtils.forceUpdate @ 0BDFDB.plugin.js:3013
(anonymous) @ PluginRepo.plugin.js:457
(anonymous) @ VM45 fs.js:171
8799fc073394b31a5a71.js:130 [BDFDB] (v2.0.3) USER_SETTINGS_VOICE_INSTALLED_LABEL not found in BDFDB.LanguageUtils.LanguageStrings
(anonymous) @ 8799fc073394b31a5a71.js:130
module.exports.InternalBDFDB.console @ 0BDFDB.plugin.js:173
module.exports.BDFDB.LogUtils.warn @ 0BDFDB.plugin.js:179
get @ 0BDFDB.plugin.js:4521
render @ PluginRepo.plugin.js:497
Xo @ 72001f09f5dc9cab20d0.js:6189
qo @ 72001f09f5dc9cab20d0.js:6189
$s @ 72001f09f5dc9cab20d0.js:6229
Gu @ 72001f09f5dc9cab20d0.js:6219
Uu @ 72001f09f5dc9cab20d0.js:6219
wu @ 72001f09f5dc9cab20d0.js:6219
Au @ 72001f09f5dc9cab20d0.js:6216
(anonymous) @ 72001f09f5dc9cab20d0.js:6161
t.unstable_runWithPriority @ 72001f09f5dc9cab20d0.js:6460
Ki @ 72001f09f5dc9cab20d0.js:6161
Xi @ 72001f09f5dc9cab20d0.js:6161
qi @ 72001f09f5dc9cab20d0.js:6161
ke @ 72001f09f5dc9cab20d0.js:6238
(anonymous) @ 72001f09f5dc9cab20d0.js:6152
Vr @ 72001f09f5dc9cab20d0.js:6152
rn @ 72001f09f5dc9cab20d0.js:6139
nn @ 72001f09f5dc9cab20d0.js:6139
t.unstable_runWithPriority @ 72001f09f5dc9cab20d0.js:6460
tn @ 72001f09f5dc9cab20d0.js:6138
r @ 8799fc073394b31a5a71.js:126
BetterVolume.plugin.js:83 Uncaught DOMException: Blocked a frame with origin "https://discord.com" from accessing a cross-origin frame.
    at betterdiscord://plugins/BetterVolume.plugin.js:83:34
    at Array.some (<anonymous>)
    at betterdiscord://plugins/BetterVolume.plugin.js:80:78
    at betterdiscord://plugins/BetterVolume.plugin.js:72:42
    at Array.every (<anonymous>)
    at betterdiscord://plugins/BetterVolume.plugin.js:72:24
    at Array.find (<anonymous>)
    at Object.find (betterdiscord://plugins/BetterVolume.plugin.js:105:40)
    at Object.byName (betterdiscord://plugins/BetterVolume.plugin.js:109:27)
    at Object.byName (betterdiscord://plugins/BetterVolume.plugin.js:170:46)
    at betterdiscord://plugins/BetterVolume.plugin.js:361:21
    at betterdiscord://plugins/BetterVolume.plugin.js:447:3
    at Object.getFileModification (<anonymous>:4:308783)
    at Object..js (<anonymous>:4:269427)
    at Function.t._load (<anonymous>:4:371557)
    at Object.loadAddon (<anonymous>:4:269584)
    at Object.loadAddon (<anonymous>:4:307108)
    at FSWatcher.<anonymous> (<anonymous>:4:267831)

**Comment by Zerthox** [comment]
The error looks a bit weird considering the plugin doesn't mess with any iframes. What are you plugins do you use?

**Comment by Sarreos** [comment]
BDFDB
BetterFormattingRedux
BetterRoleColors
CreationDate
GameActivityToggle
ImageUtilities
PluginRepo
ReadAllNotificationsButton
SplitLargeMessages
SpotifyControls 
SpotifyListenAlong
StaffTag
ThemeRep
ThemeSettings
ZeresPluginLibrary
PluginRepo

**Comment by Sarreos** [comment]
It started after I updated some plugins today

**Comment by Sarreos** [comment]
Okay, the problem just disappeared and the plugin is working right now.
