### ISSUE TITLE
1 | BetterVolume: Could not be constructed.

### ISSUE THREAD

**Issue by root-omp** [Zerthox/BetterDiscord-Plugins#95]
2 | at Object.initializeAddon (<anonymous>:4:311255)
3 | at Object.loadAddon (<anonymous>:4:273400)
4 | at Object.loadAddon (<anonymous>:4:310367)
5 | at Object.reloadAddon (<anonymous>:4:274105)
6 | at FSWatcher.<anonymous> (<anonymous>:4:271293)

**Comment by Zerthox** [comment]
Duplicate of #90. Has already been fixed with the v2.2.1 update, you can wait until it is approved for the BetterDiscord site or download it directly from the repo.
