### ISSUE TITLE
I found this issue

### ISSUE THREAD

**Issue by AlphaWolfi** [Zerthox/BetterDiscord-Plugins#96]
BetterVolume: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:311255)
    at Object.loadAddon (<anonymous>:4:273400)
    at Object.loadAddon (<anonymous>:4:310367)
    at FSWatcher.<anonymous> (<anonymous>:4:271259)

**Comment by Sukinidachi** [comment]
Its been updated about 15 hours ago, working now.

**Comment by bussybasher999** [comment]
how do I fix this?

**Comment by Sukinidachi** [comment]
The same way you installed it, just do it again.
Overwrite the existing file with the new version. Easiest way to download is straight from betterdiscord.app

**Comment by bussybasher999** [comment]
> The same way you installed it, just do it again. Overwrite the existing file with the new version. Easiest way to download is straight from betterdiscord.app

I've already tried downloading and overwriting it from the website but it still is saying that it cannot be constructed

**Comment by Zerthox** [comment]
Plugin updates have to be approved for the BetterDiscord website. Wait for it to be approved or download directly from the repo.
